### ISSUE TITLE
x64 images for selfhosting ?

### ISSUE THREAD

**Issue by accforgithubtest** [mek-x/ble-sensor-mqtt#1]
Hello there,

This is an intresting project and I am looking to host on my x86 (ubuntu) docker based set up.

Can you pls help me understand how an x86 image can be built (I am not a developer) ? Are there any pre-built images available on dockerhub / etc ? 

Thanks for creating this neat project.

**Comment by mek-x** [comment]
Hi @accforgithubtest,

thanks for taking interest in this project. I've just dusted it off a little and updated CI system to automatically build docker images for several platforms. They are stored on [gitlab's docker registry](https://gitlab.com/mek_x/ble-sensor-mqtt/container_registry). You can simply pull them to your local `docker` daemon using this command:

```
docker pull registry.gitlab.com/mek_x/ble-sensor-mqtt:latest
```

You will probably also need to run this image with `--user=root --privileged --net=host` options, since probably by default user inside the container won't have access to `hci0` device.

You can use this `docker-compose.yml` for reference:
```yml
version: '2'

services:
  ble-sensor-mqtt:
    image: registry.gitlab.com/mek_x/ble-sensor-mqtt:latest
    user: root
    network_mode: host
    privileged: true
```

I've also updated README with some of this information.
